Here is a browser link to the RMD file report knitted in HTML. It was too large to view here. 

file:///Users/edugenet/Downloads/Bellabeat-Case-Study-Report.html

### Load libraries 

```{r}
library(lubridate)
library(ggplot2)
library(tidyverse)
library(janitor)
library(purrr)
library(skimr)
library(dplyr)
library(hms)
```

### Import data

```{r}
daily_activity <- read.csv("/Users/edugenet/Desktop/Case study/Fitabase Data 4.12.16-5.12.16/dailyActivity_merged_cl.csv")

hourly_calories <- read.csv("/Users/edugenet/Desktop/Case study/Fitabase Data 4.12.16-5.12.16/hourlyCalories_merged.csv")

hourly_intensities <- read.csv("/Users/edugenet/Desktop/Case study/Fitabase Data 4.12.16-5.12.16/hourlyIntensities_merged.csv")

hourly_steps <- read.csv("/Users/edugenet/Desktop/Case study/Fitabase Data 4.12.16-5.12.16/hourlySteps_merged.csv")

daily_sleep <- read.csv("/Users/edugenet/Desktop/Case study/Fitabase Data 4.12.16-5.12.16/sleepDay_merged.csv")

weight_log <- read.csv("/Users/edugenet/Desktop/Case study/Fitabase Data 4.12.16-5.12.16/weightLoginfo_merged.csv")

heart_rate <- read.csv("/Users/edugenet/Desktop/Case study/Fitabase Data 4.12.16-5.12.16/heartrate_merged.csv")
```
 
### Data Cleaning

```{r}
#Check for correct data types, readable column names, select/reorder columns, add columns, and drop NA values.

 activity <- daily_activity %>% 
   clean_names() %>%            
   mutate(date = ymd(daily_activity$ActivityDate)) %>% 
   select(1,16,3,4,11,12,13,14,15)  

 calories <- hourly_calories %>% 
   drop_na() %>%
   clean_names() %>%
   mutate(date = ymd(hourly_calories$ActivityDate))%>%
   select(1,5,3,4)

  intensities <- hourly_intensities %>%
    clean_names() %>%
    mutate(date = ymd(hourly_intensities$ActivityDate)) %>%
    select(1,6,3,4,5)
    
  intensities$time <- format(intensities$time, format = "%H:%M:%S")
  
 steps <- hourly_steps %>% 
    clean_names() %>%
    mutate(date = ymd(hourly_steps$ActivityDate)) %>%
    select(1,5,3,4,)
    
  steps$time <- format(steps$time, format = "%H:%M:%S")
  

  sleep <- daily_sleep %>%
    clean_names %>% 
    mutate(date = ymd(daily_sleep$SleepDay)) %>%
    select(1,7,3,4,5,6)
 
 daily_sleep$time <- format(daily_sleep$time, format = "%H:%M:%S")

  weight <- weight_log %>%
    clean_names() %>%
    mutate(date = ymd(weight_log$Date)) %>%
    select(1,2,3,4,6)
 
  heartrate <-  heart_rate %>%
    clean_names() %>%
    mutate(date = ymd(heart_rate$date))
    
    heartrate$time <- format(heartrate$time, format = "%H:%M:%S")  
```   

## Data Exploration 

```{r}
# Check the unique number of entrys by the users for each category.

activity %>%
  group_by(activity$id) %>%
  summarise(number_of_entry = n())

sleep %>%
  group_by(id) %>%
  summarise(number_of_entry = n())

weight %>%
  group_by(id) %>%
  summarise(number_of_entry = n())

steps %>%
  group_by(id) %>%
  summarise(number_of_entry = n()/24) 

#calories %>%
  #group_by(id) %>%
  #summarise(number_of_entry = n()/24)

intensities %>%
  group_by(id) %>%
  summarise(number_of_entry = n()/24) 
```

```{r}
#Check the number of participants in each cataegory

n_distinct(activity$id)
n_distinct(intensities$id)
n_distinct(calories$id)
n_distinct(sleep$id)
n_distinct(steps$id)
n_distinct(weight$id)
n_distinct(heartrate$id)
```
k the relationship between activity and sleep. 

```{r}
#Check relationship between activity and sleep.

sleep_steps <- merge(sleep, steps, by.x = "id", by.y = "id")

sleep_steps %>%
  select(total_minutes_asleep) %>%
  summary()
  
activity %>%
  select(lightly_active_minutes, 
         fairly_active_minutes,
         very_active_minutes, 
         sedentary_minutes) %>%
  summary()
```
## Visualization

```{r}
#summarise and visualize the relationship between steps and calories

activity%>%
  select(total_steps, calories) %>%
  summary()

ggplot(data = activity, 
       mapping = aes(x = total_steps,
                     y = calories)) +
  geom_point(size = 2, alpha = 0.5) + 
  geom_smooth(color = "red") +
  labs(title = "Fitbit Fitness Data: Steps vs Calories", 
       subtitle = "Sample for total steps and calories burned", 
       caption = "Data collected by Fitbit Fitness Tracker", x = "Steps", y = "Calories") + 
  annotate("text", x = 36019, y = 0, 
           label= " Max steps: 36019 ", size = 2) +
  annotate("text", x = 0, y = 4900, 
           label= " Max cal: 4900 ", size = 2) +
  theme_bw()

```

```{r}
# Create a new table showing the min, avg, and max heartrate per id. 

heartrate_tab <- heartrate %>%
  group_by(id) %>%
  summarise( min_rate =  min(value), 
             Avg_rate = mean(value),
             max_rate = max(value))  %>%
  arrange(Avg_rate) %>%
  view()
```

```{r}
#Add all the active minutes including very, fairly and lightly active minutes and compare to sedentary minutes

activity %>%
  drop_na() %>%
  mutate(total_active_min = rowSums(activity[, c(3,4,5)], na.rm=TRUE)) %>%
  ggplot(activity, mapping= aes(total_active_min, sedentary_minutes)) +
  geom_point(size = 2, color  = "purple", alpha = 0.5 ) +
  geom_smooth(method= lm) +
  labs(x = "Active",
       y = "Sedentary",
       title = "Fitbit Fitness Data: Sedentary minutes vs Active minutes ",
       caption = "Kaggle: Data collected by Fitbit Fitness Tracker") +
  theme_bw()                   
``` 

#Now let’s analyze the BMI range.

```{r}
    weight2 <- merge(weight, intensities, by.x = "id", by.y = "id")
    head(weight2)
```

```{r}
#Catagorize BMI numeric value by the standard range
 
    weight2 <- weight %>%
    group_by(id) %>%
    mutate(bmi = if_else(bmi >= 18.5 & bmi <= 24.9, "Healthy weight", 
           if_else(bmi < 18.5, "Under weight", 
           if_else(bmi >= 25 & bmi <= 29.9, "Over weight",
           if_else(bmi >= 30, "Obese", "Wrong Value"))))) 
    
    weight2 %>%  
      drop_na(bmi) %>%
      ggplot(aes(x = bmi, fill = bmi)) + 
      geom_bar(position = "dodge", alpha = 0.5) + 
      labs( x = "BMI",
            Y = NULL, 
            title = "Fitbit Fitness Data: BMI status",
            caption = "Kaggle: Data collected by Fitbit Fitness Tracker") +
      theme_bw() +
      theme(panel.grid.major = element_blank())
    
    weight2 %>%
      group_by(bmi) %>%
      group_by(bmi) %>%
      summarise(n_distinct(id))
```                                                         

THANK YOU for your time! 
